-- Add More Brands to Database
-- Run this SQL to add popular electronic brands

INSERT INTO brands (brand_name, created_at) VALUES
('Philips', NOW()),
('Samsung', NOW()),
('Walton', NOW()),
('LG', NOW()),
('Sony', NOW()),
('Panasonic', NOW()),
('Hitachi', NOW()),
('Sharp', NOW()),
('Toshiba', NOW()),
('Haier', NOW()),
('TCL', NOW()),
('Xiaomi', NOW()),
('Whirlpool', NOW()),
('Bosch', NOW()),
('Siemens', NOW()),
('Electrolux', NOW()),
('Kenwood', NOW()),
('Braun', NOW()),
('Tefal', NOW()),
('Moulinex', NOW()),
('Bajaj', NOW()),
('Prestige', NOW()),
('Butterfly', NOW()),
('Havells', NOW()),
('Crompton', NOW()),
('Usha', NOW()),
('Orient', NOW()),
('Maharaja', NOW()),
('Pigeon', NOW()),
('Inalsa', NOW()),
('Glen', NOW()),
('Morphy Richards', NOW()),
('Russell Hobbs', NOW()),
('Black+Decker', NOW()),
('Cuisinart', NOW()),
('KitchenAid', NOW()),
('Breville', NOW()),
('Ninja', NOW()),
('Instant Pot', NOW()),
('Crock-Pot', NOW()),
('Hamilton Beach', NOW()),
('Oster', NOW()),
('Sunbeam', NOW()),
('Preethi', NOW()),
('Power Guard', NOW()),
('Vision', NOW()),
('Minister', NOW()),
('Singer', NOW()),
('Miyako', NOW()),
('Jamuna', NOW())
ON DUPLICATE KEY UPDATE brand_name = VALUES(brand_name);

-- Note: This uses ON DUPLICATE KEY UPDATE to avoid duplicate entries
-- if brands already exist in the database
